modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="gravelsdynamicdynamosandmore" #mandatory
version="0.1" #mandatory
displayName="Gravel's Dynamic Dynamos and More" #mandatory
logoFile="GDDMLOGO.png" #optional
credits="Thanks to Daniel Richardi for being a great teacher, Harry Talks on youtube for a super useful tutorial, and the Forge API dev(s) for their awesome(ly written) code" #optional
authors="Gravel__" #optional
description='''
Gravel's Dynamic Dynamos and More is a mod made in an attempt to streamline, unify and have options when it comes to power generation.
The mod provides a planned 20+ new blocks, most of them power generation, and new materials to make these blocks. 
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gravelsdynamicdynamosandmore]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.gravelsdynamicdynamosandmore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
